openapi: 3.1.0
tags:
  - name: Tipo de Dano
    description: Operações relacionadas ao recurso de Tipo de Dano

paths:
  /damage-type:
    get:
      summary: Obter Lista de Tipos de Dano
      tags:
        - Tipo de Dano
      responses:
        '200':
          description: Tipos de Dano encontrados com sucesso
          content:
            application/json:
              example:
                message: Tipos de Dano encontrados com sucesso
                data:
                  - type: Corte
                  - type: Impacto
                  - type: Perfuração

    post:
      summary: Criar Novo Tipo de Dano
      tags:
        - Tipo de Dano
      description: Cria um novo tipo de dano com base nos dados fornecidos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: Fogo
      responses:
        '201':
          description: Tipo de Dano criado com sucesso
          content:
            application/json:
              example:
                message: Tipo de Dano criado com sucesso
                data:
                  type: Fogo
        '400':
          description: Erro na validação dos dados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationDataError'
  /damage-type/{id}:
    get:
      summary: Obter Detalhes do Tipo de Dano por ID
      tags:
        - Tipo de Dano
      description: Retorna os detalhes de um tipo de dano específico por ID.
      parameters:
        - in: path
          name: id
          required: true
          description: ID do tipo de dano a ser obtido
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Tipo de Dano encontrado com sucesso
          content:
            application/json:
              example:
                message: Tipo de Dano encontrado com sucesso
                data:
                  type: Fogo
        '404':
          description: Tipo de Dano não encontrado
          content:
            application/json:
              example:
                message: Tipo de Dano não encontrado
    patch:
      summary: Atualizar Tipo de Dano por ID
      tags:
        - Tipo de Dano
      description: Atualiza um tipo de dano existente com base nos dados fornecidos.
      parameters:
        - in: path
          name: id
          required: true
          description: ID do tipo de dano a ser atualizado
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: Gelo
      responses:
        '200':
          description: Tipo de Dano atualizado com sucesso
          content:
            application/json:
              example:
                message: O tipo de dano foi atualizado
                data:
                  type: Gelo
        '400':
          description: Erro na validação dos dados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationDataError'
        '404':
          description: Tipo de Dano não encontrado
          content:
            application/json:
              example:
                message: Tipo de Dano não encontrado
    delete:
      summary: Excluir Tipo de Dano por ID
      tags:
        - Tipo de Dano
      description: Exclui um tipo de dano existente com base no ID fornecido.
      parameters:
        - in: path
          name: id
          required: true
          description: ID do tipo de dano a ser excluído
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Tipo de Dano excluído com sucesso
        '400':
          description: Erro na validação dos dados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationDataError'
        '404':
          description: Tipo de Dano não encontrado
          content:
            application/json:
              example:
                message: Tipo de Dano não encontrado
